### ISSUE TITLE
Problem loading Parlitools Package

### ISSUE THREAD

**Issue by ljeff99** [evanodell/parlitools#4]
Hi,

I am a student and have been working on some UK elections analyses recently, and to aid in doing this I have been attempting to use your package. Unfortunately, after having seemingly succeeded in installing it, when I try to load the package I get:

Error: package or namespace load failed for ‘parlitools’ in namespaceExport(ns, exports):
 undefined exports: st_agr<-, st_crs<-, st_geometry<-, st_precision<-, .degAxis, .get_layout, .image_scale, .image_scale_factor, .stop_geos, NA_agr_, NA_bbox_, NA_crs_, NA_m_range_, NA_z_range_, as_Spatial, gdal_crs, gdal_inv_geotransform, gdal_metadata, gdal_polygonize, gdal_rasterize, gdal_read, gdal_subdatasets, gdal_utils, gdal_write, get_key_pos, plot_sf, rawToHex, read_sf, sf.colors, sf_add_proj_units, sf_extSoftVersion, sf_proj_info, sf_project, st_agr, st_area, st_as_binary, st_as_grob, st_as_sf, st_as_sfc, st_as_text, st_axis_order, st_bbox, st_bind_cols, st_boundary, st_buffer, st_cast, st_centroid, st_collection_extract, st_combine, st_contains, st_contains_properly, st_convex_hull, st_coordinates, st_covered_by, st_covers, st_crop, st_crosses, st_crs, st_difference, st_dimension, st_disjoint, st_distance, st_drivers, st_drop_geometry, st_equals, st_equals_exact, st_filter, st_geometry

I also get a warning for some S3 methods as well.

I have tried various methods but nothing seems to have solved it. Of course this may well not be the right place to put this (am new to this so apologies if so), but I hoped as the person who created the package you would have some insight. So if you are able to offer any advice I would be most grateful.

**Comment by evanodell** [comment]
try `install.packages(“sf”)`

**Comment by ljeff99** [comment]
Brilliant, that's fixed it thank you!
